#! /usr/bin/env python
# encoding: utf-8
def compile_tests(tests):
    for t in tests:
        test_name = str(t)
        bld.program(features = 'cxx cxxprogram test',
                    source   = test_name,
                    target   = test_name.replace(".cxx", ""),
                    lib      = ['pthread', 'gtest', 'gtest_main'],
                    includes = ". .. ../src")

compile_tests(bld.path.ant_glob("*test.cxx"))
