#! /usr/bin/env python
# encoding: utf-8
from waflib.Tools import waf_unit_test
from colorize import summary

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')
    opt.load('waf_unit_test')

def configure_gtest(conf):
    conf.check(header_name="gtest/gtest.h")

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('waf_unit_test')
    configure_gtest(conf)
    conf.env.INCPATHS = ['src']

def build(bld):
    bld.recurse('src test')
    bld.add_post_fun(summary)
    bld.options.all_tests = True
